#dynamic_title = true
#theme = "Hyper"

[colors.bright]
black = "#808080"
blue = "#0066ff"
cyan = "#00ffff"
green = "#33ff00"
magenta = "#cc00ff"
red = "#fe0100"
white = "#FFFFFF"
yellow = "#feff00"

[colors.cursor]
cursor = "#ffffff"
text = "#F81CE5"

[colors.normal]
black = "#000000"
blue = "#0066ff"
cyan = "#00ffff"
green = "#33ff00"
magenta = "#cc00ff"
red = "#fe0100"
white = "#d0d0d0"
yellow = "#feff00"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

#[font]
#size = 10.0
#[font.bold]
#family = "MSX Screen 0 New"
#style = "Bold"
#[font.bold_italic]
#family = "MSX Screen 0 New"
#style = "Bold Italic"
#[font.italic]
#family = "MSX Screen 0 New"
#style = "Italic"
#[font.normal]
#family = "MSX Screen 0 New"
#style = "Regular"

#!!!!

[font]
size = 10.0
[font.bold]
family = "BmPlus IBM VGA 8x16"
style = "Bold"
[font.bold_italic]
family = "BmPlus IBM VGA 8x16"
style = "Bold Italic"
[font.italic]
family = "BmPlus IBM VGA 8x16"
style = "Italic"
[font.normal]
family = "BmPlus IBM VGA 8x16"
style = "Regular"

#[font]
#size = 10.0
#[font.bold]
#family = "PxPlus HP 100LX 6x8"
#style = "Bold"
#[font.bold_italic]
#family = "PxPlus HP 100LX 6x8"
#style = "Bold Italic"
#[font.italic]
#family = "PxPlus HP 100LX 6x8"
#style = "Italic"
#[font.normal]
#family = "PxPlus HP 100LX 6x8"
#style = "Regular"

[window]
opacity = 0.9

[window.padding]
x = 0
y = 0
